name: "CodeQL"

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CODEQL_ENABLE_EXPERIMENTAL_FEATURES_SWIFT: true

jobs:
  analyze:
    name: Analyze
    runs-on: macos-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'swift' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
    
    - name: Build
      run: xcodebuild "-project" "secant.xcodeproj" "-scheme" "secant-testnet" -destination "platform=iOS,name=iPhone 14,OS=16.2" "clean" "test"

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"