name: Zashi unit tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    permissions:
          contents: read
    
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      timeout-minutes: 1
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_15.2.app/Contents/Developer'
    - name: Run tests
      timeout-minutes: 5
      run: xcodebuild test -scheme secant-testnet -project secant.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=15.0'
